src/drivers/ports/avr/adc_port.h
src/drivers/ports/avr/adc_port.i

The 2560 requires the MUX5 bit of ADCSRB be set when selecting port K as the source for the ADC.
Without this selecting analog pins 8-15 actually gave readings from pins 0-7.

Fix analog 8-15 on Arduino Mega

---

src/inet/mqtt_client.c
tst/inet/mqtt_client/main.c

buf[7] is CLEAN_SESSION, not buf[8]
buf[8] and buf[9] are keepalive
buf[10] and buf[11] are connect payload (is must required)

bugfix for mqtt-client

---

doc/library-reference/drivers/led_7seg_ht16k33.rst
examples/led_7seg_ht16k33/Makefile
examples/led_7seg_ht16k33/config.h
examples/led_7seg_ht16k33/main.c
src/config_default.h
src/drivers/led_7seg_ht16k33.c
src/drivers/led_7seg_ht16k33.h
src/drivers/led_7seg_ht16k33_numbertable.i
src/simba.h
src/simba.mk
tst/drivers/led_7seg_ht16k33/Makefile
tst/drivers/led_7seg_ht16k33/config.h
tst/drivers/led_7seg_ht16k33/main.c

This driver allows controlling Adafruit 0.56" 4-Digit 7-Segment
Display w/I2C Backpack.
I tried to follow coding conversion from other files, but not sure how much I got it right.
Do comment on the patch etc. and I can fix things instead of you having to do it later.
For now only added it to the nodemcu board, as that's the one I have tested it on. That said, I see no reason it shouldn't work on other boards using i2c_soft driver.
PS. I did the work entirely in my own spare time, but the simple way to release patches like this means my dayjob retains copyright, and for code which is under MIT this shouldn't really matter.

Add LED 7-Segment HT16K33 driver.

---

src/config_default.h

This change sets valid size and offset for the WEMOS D1 mini 4MB
flash. Without this, formatting the file system ends up overwriting
the application on the flash.

Fix flash filesystem support on WEMOS D1 mini.

---

examples/ds18b20/main.c

Without this, if the sensor fails to respond, the code will print
uninitialized memory which may end up crashing the MCU.

In the DS18B20 example, add more error checking.

---

setup.sh

The UNIX standard string operator in test / "[" is "=". Some shells
like bash have added "==", but it fails e.g. in zsh.

Fix setup.sh conditional to work in all shells.

---

src/config_default.h
src/drivers/ds18b20.c
src/simba.mk

This change also fixes alignment of struct ds18b20_scratchpad_t by
adding PACKED.
The ESP8266 uses different alignment than the 8 bit AVR (where DS18B20
worked fine), which resulted in struct ds18b20_scratchpad_t being
alligned incorrectly, causing the CRC check to fail.  That took a
while to track down as the root cause.
Tested on WEMOS D1 mini, Arduino Nano.

Add support for the DS18B20 driver on ESP8266 boards.

---

src/drivers/ports/sam/exti_port.i

This works well for my local Arduino Due board to detect both Rising and Falling edges.

Enable EXTI_PORT_TRIGGER_BOTH_EDGES for Arduino SAM

---

doc/library-reference/drivers/esp_wifi.rst
examples/esp_wifi/station/main.c
examples/esp_wifi/station_softap/main.c
src/drivers/esp_wifi/station.c
src/drivers/esp_wifi/station.h
src/drivers/ports/esp/esp_wifi_port/station.i
src/drivers/ports/esp32/esp_wifi_port/station.i
src/inet/network_interface/driver/esp.c
src/inet/network_interface/wifi.h
tst/drivers/esp_wifi/main.c

Hello,
[noob alert]
Seems like Simba doesn't have an option to specify WiFi station BSSID to connect to. This is important when connecting to multi-AP WiFi network because SDK is too dumb to figure out which AP to connect to on its own.
Espressiv SDK does support this via the station_config struct. I'm wondering whether it's planned to add this into Simba, or am I just missing something?

ESP8266 - specifying station BSSID to connect to

---

src/inet/socket.c

Hi!
Found a problem with the HTTP server. http_server_response_write() never returns if transmission is interrupted on client side - subsequent page requests are not being responded to. This is with ESP8266 - not sure whether other ports are affected. Steps to reproduce:
1) Flash the HTTP server example
2) Ctrl+C while curl is downloading page
```bash
eimis@e6430 ~/Projects/simba $ curl -i http://192.168.1.183
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 9748
<!DOCTYPE html> <html> <head> <meta ^C
```
3) Subsequent curl calls never return or produce:
```bash
eimis@e6430 ~/Projects/simba $ curl -i http://192.168.1.183
curl: (56) Recv failure: Connection reset by peer
```
My guess is that chan_write() inside of http_server_response_write() never returns. I'd surely investigate …

http_server_response_write() never returns if transmission is interrupted [ESP8266]

---

src/inet/socket.c

This makes it faster to find out what's going on when trying to use
sockets on an unsupported architecture.

Return -ENOSYS instead of -1 if architecture has no socket support.

---

src/inet/mqtt_client.c
src/inet/mqtt_client.h
tst/inet/mqtt_client_network/main.c

The default simply logs an error using the existing log object.
In many cases the isn't a lot useful to do in the error call back, so
just logging an error by default means less code in the common case.
Use new NULL on_error callback in mqtt_client_network test, and make
it possible to override REMOTE_HOST_IP and REMOTE_HOST_PORT on the
command line.

mqtt_client: Make on_error callback optional by providing a default.

---

src/mcus/esp8266/mcu.c

This makes SCL = gpio5 and SDA = gpio4, which matches both WEMOS D1
Mini and Adafruit Feather HUZZAH ESP8266 documented I2C pins.
Those were the two ESP8266 boards I found which defined default I2C
pins, probably because they both supports shields (so it matters which
pins you use).
While the Adafruit Feather HUZZAH ESP8266 is not yet supported by
Simba, it's likely to be in the future...
References:
https://wiki.wemos.cc/products:d1:d1_mini
https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/pinouts

Switch around the esp8266 default i2c0 SCL/SDA pins.

---

doc/library-reference/inet/mqtt_client.rst
examples/mqtt_client/Makefile
examples/mqtt_client/main.c
src/inet/mqtt_client.c

The example is heavily based on tst/inet/mqtt_client_network/.
This change include the very basic initization in the mqtt_client
documentation page, as I think it makes the API more understandable.
More advanced features can be added to the example later, this should
get people going.
Closes eerimoq/simba#108.

Add an mqtt_client example and improve documentation.

---

doc/boards/arduino_mega.rst
doc/boards/arduino_nano.rst
doc/boards/arduino_pro_micro.rst
doc/boards/arduino_uno.rst
doc/boards/esp01.rst
doc/boards/esp12e.rst
doc/boards/esp32_devkitc.rst
doc/boards/huzzah.rst
doc/boards/linux.rst
doc/boards/maple_esp32.rst
doc/boards/nano32.rst
doc/boards/nodemcu.rst
doc/boards/photon.rst
doc/boards/stm32f3discovery.rst
doc/boards/stm32vldiscovery.rst
doc/boards/wemos_d1_mini.rst
doc/developer-guide/testing-suites.rst
src/boards/wemos_d1_mini/board.mk

Regenerate docs so new product page link is picked up.

Fix link to WEMOS D1 mini product page.

---

src/drivers/sht3xd.c

This is used for driver internal debugging instead of the previous
The macro attempts to require as little boilerplate as possible, so as
many log lines as possible can be on a single line for increased
readability.
While here adjust a few of the log messages.

SHT3XD: Create and use internal DLOG macro.

---

src/inet/mqtt_client.c
tst/inet/mqtt_client/main.c

In the current mqtt_client, when the keep alive expires there is no
way to reconnect, so there is no advantage in a short keep alive
period as mqtt_client just silently stops working at that point.
This is mostly a bandaid until larger rework of connection options is
done for #109, #110 and #113. Since that rework is required, this
change is intentionally kept simple and does not allow user override
of the keep alive interval.
While here use BTASSERTI in a number of cases to make test output more
usable.
This was tested using mqtt_client, and mqtt_client_network against a
real MQTT broker (Mosquitto).

Change mqtt_client keep alive from 10s to 5m.

---

make/platformio.sconscript
make/platformio/platformio.py

See issue #131 
With platformio, solves the problem to set the application name passed as an argument to simbagen.py script. 
It uses the environment variable _APP_NAME_ in [platformio.sconscript](https://github.com/eerimoq/simba/blob/master/make/platformio.sconscript#L3964) (default is _app_name_), so with this patch application name can be set with:
`APP_NAME='MyApp' pio run`
or 
```
export APP_NAME='MyApp'
pio run
```

Platformio: get application name from APP_NAME environment variable.

---

src/drivers/basic/watchdog.h
src/drivers/ports/avr/watchdog_port.i

Simba framework uses milliseconds to set the watchdog timeout. AVR uses a prescaler value.

Set the prescaler from milliseconds in avr watchdog.

---

bin/simbagen.py
make/platformio.sconscript
make/platformio/platformio.py

discussed [on forum](https://forum.simbaos.org/showthread.php?tid=17)
usage:
1. add valid *.ini file with settings
2. set relative or absolute path to this file in board's options, for example:
```
[env:esp12e]
settings_path = ../settings/12e.ini
[env:esp8285]
settings_path = ~/settings/8285.ini
```

Add settings module support for PlatformIO

---

doc/library-reference/inet/mqtt_client.rst
examples/mqtt_client/main.c
src/inet/mqtt_client.c
src/inet/mqtt_client.h
tst/inet/mqtt_client/main.c
tst/inet/mqtt_client_network/main.c

This allows setting client id, username, password, and Last Will and
Testament in MQTT connection options.
Setting this is done through a parameter to
mqtt_client_connect(). While this changes the API, it seems like the
best aproach as it allows the client not to have to keep any state for
the new options and therefor do not increase memory consumption other
than during connect.
The change is made so it's very easy for existing code to be updated,
as it simply need to change connect call from:
mqtt_client_connect(client);
to:
mqtt_client_connect(client, NULL);
to preserve existing behaviour.
While here update the documentation.
This has been tested against real MQTT brokers io.adafruit.com and
test.mosquitto.org.
Fixes #109.
Fixes #110.

mqtt_client: Add support for connection options.

---

doc/library-reference/drivers/network/i2c.rst
doc/library-reference/mcus/esp32.rst
doc/library-reference/mcus/esp8266.rst

- Update i2c page to say i2c_soft provides compat.
- Add pin information to ESP32 and ESP8266 pages.

Improve I2C soft compat documentation.

---

src/drivers/network/esp_wifi.h
src/inet/network_interface/driver/esp.c

Without this the high level network_interface_wifi, including users
of CONFIG_START_NETWORK, may end up with an access point running using
the default name (e.g. ESP_XXXXXX) which does not seem to be
intentional.
A user can still explicitly enable the softap mode and use
network_interface_wifi.
While here add some comments to esp_wifi_op_mode_t and the esp driver
making it more clear how some of the code and enum values work / are
used.

Initialize ESP driver to station mode by default.

---

make/platformio/platformio.py

Add WeMos D1 mini to  supported boards.

add wemos d1 mini to supported platforms

---

make/gnu/esp.mk

This way I can set up my own esptool, when for example compiling on raspberry pi.

allow to override ESPTOOL variable

---

src/drivers/sensors/dht.c

Bytes are being read from the sensor in wrong order. Also each byte is shifted left to many times. This PR fixes that.

fix data order and shifting

---

src/drivers/basic/analog_output_pin.c

Fixes #175
The analog_output_pin_init function initialize the pwm pin. Then, analog_output_pin_write configure duty cycle of the PWM module but doesn't set frequency (via setting compare register). The code for configuring compare register is placed at the pwm_port_set_frequency function.
The pwm_start function sets frequency + duty cycle (by calling pwm_port_set_frequency). So, by calling the pwm_start function between initialization and write fix the issue.
I'm not sure where to place this call in the analog_output_pin_init or analog_output_pin_write with some handling if freq. is already set.

Fix missing PWM frequency configuration for AVR port

---

src/config_default.h
src/drivers/sensors/dht.c
src/drivers/sensors/dht.h
src/kernel/ports/esp/gnu/time_port.i

Enables dht module for esp8266 mcu. Also adds new function dht_read11() to read data from DHT11 sensor, which requires slightly different decoding.

Enable DHT sensor driver for esp8266

---

bin/dbgen.py
bin/docgen.py
doc/user-guide/configuration.rst

Add missing documentation about serial port settings #188.
I thought that there could be another default settings which need to be mentioned, so, I added the Serial port section under the Default Settings section.

Add Default Settings section into User Guide docs

---

src/drivers/sensors/dht.c

Since there is pull-up resistor, we do not have to set pin high manually.

Remove spare pin manipulation.
